package com.example.rrms.domain;

public enum Permission {
    //platform (SUPER_ADMIN)
    TENANT_CREATE, TENANT_VIEW, TENANT_UPDATE, OWNER_CREATE, PLATFORM_AUDIT_VIEW,

    //Owner
    REVENUE_VIEW, REPORT_VIEW, ROLE_MANAGE, RESORT_CONFIG, AUDIT_VIEW, SETTINGS_MANAGE,
    MANAGEMENT_CREATE, MANAGEMENT_VIEW,

    //Management
    TASK_CREATE, TASK_ASSIGN, TASK_VIEW, TASK_INSPECT, TASK_VERIFY, TASK_REJECT, TASK_REASSIGN,
    STAFF_CREATE, STAFF_VIEW, STAFF_UPDATE,
    GUEST_CREATE, GUEST_VIEW, GUEST_UPDATE,
    BOOKING_CREATE, BOOKING_VIEW, BOOKING_UPDATE,

    //Receptionist
    BOOKING_MANAGE, CHECK_IN, CHECK_OUT,

    //Operational Staff
    TASK_VIEW_ASSIGNED, TASK_START, TASK_UPDATE, TASK_COMPLETE,

    //Guest
    GUEST_PROFILE_VIEW, GUEST_PROFILE_UPDATE, GUEST_BOOKING_VIEW,
    GUEST_BOOKING_CANCEL,
    GUEST_ADDON_VIEW, GUEST_ADDON_REQUEST, GUEST_BILLING_VIEW,
    GUEST_LOYALTY_VIEW, GUEST_LOYALTY_REDEEM

}
